# Generated by Django 3.2.2 on 2021-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_title', models.CharField(max_length=100)),
                ('short_summary', models.TextField()),
            ],
        ),
    ]
