# Generated by Django 3.2.2 on 2021-09-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0006_feature_lnk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='lnk',
            field=models.CharField(default="{% url 'login' %}", max_length=20),
        ),
    ]
